# Generated by Django 3.2.9 on 2021-12-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=10)),
                ('url_path', models.CharField(max_length=200)),
                ('data', models.TextField()),
                ('expected', models.TextField()),
                ('modify_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
